/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as AuthenticatedShellIndexRouteImport } from './routes/_authenticated/_shell.index'
import { Route as AuthenticatedShellSettingsRouteImport } from './routes/_authenticated/_shell.settings'
import { Route as AuthenticatedShellResearchRouteImport } from './routes/_authenticated/_shell.research'
import { Route as AuthenticatedShellProfileRouteImport } from './routes/_authenticated/_shell.profile'
import { Route as AuthenticatedShellPlannerRouteImport } from './routes/_authenticated/_shell.planner'
import { Route as AuthenticatedShellMeetingRouteImport } from './routes/_authenticated/_shell.meeting'
import { Route as AuthenticatedShellEmailRouteImport } from './routes/_authenticated/_shell.email'
import { Route as AuthenticatedShellChatRouteImport } from './routes/_authenticated/_shell.chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShellIndexRoute = AuthenticatedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellSettingsRoute =
  AuthenticatedShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellResearchRoute =
  AuthenticatedShellResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProfileRoute =
  AuthenticatedShellProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellPlannerRoute =
  AuthenticatedShellPlannerRouteImport.update({
    id: '/planner',
    path: '/planner',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellMeetingRoute =
  AuthenticatedShellMeetingRouteImport.update({
    id: '/meeting',
    path: '/meeting',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellEmailRoute = AuthenticatedShellEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellChatRoute = AuthenticatedShellChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedShellIndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedShellChatRoute
  '/email': typeof AuthenticatedShellEmailRoute
  '/meeting': typeof AuthenticatedShellMeetingRoute
  '/planner': typeof AuthenticatedShellPlannerRoute
  '/profile': typeof AuthenticatedShellProfileRoute
  '/research': typeof AuthenticatedShellResearchRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedShellIndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedShellChatRoute
  '/email': typeof AuthenticatedShellEmailRoute
  '/meeting': typeof AuthenticatedShellMeetingRoute
  '/planner': typeof AuthenticatedShellPlannerRoute
  '/profile': typeof AuthenticatedShellProfileRoute
  '/research': typeof AuthenticatedShellResearchRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/_shell/chat': typeof AuthenticatedShellChatRoute
  '/_authenticated/_shell/email': typeof AuthenticatedShellEmailRoute
  '/_authenticated/_shell/meeting': typeof AuthenticatedShellMeetingRoute
  '/_authenticated/_shell/planner': typeof AuthenticatedShellPlannerRoute
  '/_authenticated/_shell/profile': typeof AuthenticatedShellProfileRoute
  '/_authenticated/_shell/research': typeof AuthenticatedShellResearchRoute
  '/_authenticated/_shell/settings': typeof AuthenticatedShellSettingsRoute
  '/_authenticated/_shell/': typeof AuthenticatedShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/email'
    | '/meeting'
    | '/planner'
    | '/profile'
    | '/research'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/email'
    | '/meeting'
    | '/planner'
    | '/profile'
    | '/research'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_shell'
    | '/_authenticated/_shell/chat'
    | '/_authenticated/_shell/email'
    | '/_authenticated/_shell/meeting'
    | '/_authenticated/_shell/planner'
    | '/_authenticated/_shell/profile'
    | '/_authenticated/_shell/research'
    | '/_authenticated/_shell/settings'
    | '/_authenticated/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_shell/': {
      id: '/_authenticated/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings': {
      id: '/_authenticated/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedShellSettingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/research': {
      id: '/_authenticated/_shell/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedShellResearchRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/profile': {
      id: '/_authenticated/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedShellProfileRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/planner': {
      id: '/_authenticated/_shell/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedShellPlannerRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/meeting': {
      id: '/_authenticated/_shell/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof AuthenticatedShellMeetingRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/email': {
      id: '/_authenticated/_shell/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedShellEmailRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/chat': {
      id: '/_authenticated/_shell/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedShellChatRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
  }
}

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellChatRoute: typeof AuthenticatedShellChatRoute
  AuthenticatedShellEmailRoute: typeof AuthenticatedShellEmailRoute
  AuthenticatedShellMeetingRoute: typeof AuthenticatedShellMeetingRoute
  AuthenticatedShellPlannerRoute: typeof AuthenticatedShellPlannerRoute
  AuthenticatedShellProfileRoute: typeof AuthenticatedShellProfileRoute
  AuthenticatedShellResearchRoute: typeof AuthenticatedShellResearchRoute
  AuthenticatedShellSettingsRoute: typeof AuthenticatedShellSettingsRoute
  AuthenticatedShellIndexRoute: typeof AuthenticatedShellIndexRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellChatRoute: AuthenticatedShellChatRoute,
  AuthenticatedShellEmailRoute: AuthenticatedShellEmailRoute,
  AuthenticatedShellMeetingRoute: AuthenticatedShellMeetingRoute,
  AuthenticatedShellPlannerRoute: AuthenticatedShellPlannerRoute,
  AuthenticatedShellProfileRoute: AuthenticatedShellProfileRoute,
  AuthenticatedShellResearchRoute: AuthenticatedShellResearchRoute,
  AuthenticatedShellSettingsRoute: AuthenticatedShellSettingsRoute,
  AuthenticatedShellIndexRoute: AuthenticatedShellIndexRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
